const PEOPLE = {
    GET_ALL: "PEOPLE_GET_ALL",
    GET_ALL_SUCCESS: "PEOPLE_GET_ALL_SUCCESS",
    GET_ALL_FAIL: "PEOPLE_GET_ALL_FAIL",
}

const PERSON = {
    GET_BY_ID: "PERSON_GET_BY_ID",
    GET_BY_ID_SUCCESS: "PERSON_GET_BY_ID_SUCCESS",
    GET_BY_ID_FAIL: "PERSON_GET_BY_ID_FAIL",

    CREATE: "PERSON_CREATE",
    CREATE_SUCCESS: "PERSON_CREATE_SUCCESS",
    CREATE_FAIL: "PERSON_CREATE_FAIL",
}

const ERRORS = {
    CLOSE: "ERRORS_CLOSE",
    CLOSE_SUCCESS: "ERRORS_CLOSE_SUCCESS",
}

export {PEOPLE, PERSON, ERRORS};